# Generated by Django 4.0.5 on 2022-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
