# Generated by Django 4.0.5 on 2022-07-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders_phone_alter_orders_address_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
