# Generated by Django 4.0.5 on 2022-07-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_update_orderupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdate',
            new_name='Update',
        ),
    ]
